// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-btoPR6_4NWVdEz6bnSoqmw1t_1Rho6M',
    appId: '1:495269148336:web:1780341c6f467a0b89ad75',
    messagingSenderId: '495269148336',
    projectId: 'easypark-app-groep8-70ab2',
    authDomain: 'easypark-app-groep8-70ab2.firebaseapp.com',
    storageBucket: 'easypark-app-groep8-70ab2.appspot.com',
    measurementId: 'G-0BNVC1NNL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXfyW7JdGRIVUrHYwmDNqYpX_OGvJGgcs',
    appId: '1:495269148336:android:48247894b606b84e89ad75',
    messagingSenderId: '495269148336',
    projectId: 'easypark-app-groep8-70ab2',
    storageBucket: 'easypark-app-groep8-70ab2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaBc-ErZ8ihnKWyg395Jk2f4WtSvgHV8Q',
    appId: '1:495269148336:ios:b0b234cbc236f09289ad75',
    messagingSenderId: '495269148336',
    projectId: 'easypark-app-groep8-70ab2',
    storageBucket: 'easypark-app-groep8-70ab2.appspot.com',
    iosClientId: '495269148336-8k1bjlrf8r72fs7uo79decnk00qnpbua.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyparkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaBc-ErZ8ihnKWyg395Jk2f4WtSvgHV8Q',
    appId: '1:495269148336:ios:b0b234cbc236f09289ad75',
    messagingSenderId: '495269148336',
    projectId: 'easypark-app-groep8-70ab2',
    storageBucket: 'easypark-app-groep8-70ab2.appspot.com',
    iosClientId: '495269148336-8k1bjlrf8r72fs7uo79decnk00qnpbua.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyparkApp',
  );
}
